Repository openthread/silk, pull requests merged in 2020-08, with the labels that each got.

#45 Fix testcase OTNS Manager check
  silk/tests/testcase.py
Labels: bug

#43 Set up Python virtualenv
  .gitignore
  Makefile
  README.md
  bootstrap.sh
  requirements.txt
Labels: dependencies

#46 Add test case name display
  bootstrap.sh
  silk/tests/silk_replay.py
  silk/tests/testcase.py
Labels: enhancement

#47 Add default option to keep all nodes stationary
  silk/tools/otns_manager.py
Labels: enhancement

#48 Add build actions
  .github/workflows/build.yml
  bootstrap.sh
Labels: continuous-integration

#50 Fix LGTM warnings
  silk/device/system_call_manager.py
  silk/node/base_node.py
  silk/node/fifteen_four_dev_board.py
  silk/node/openthread_sniffer.py
  silk/tools/usbdevice.py
  silk/tools/watchable.py
  silk/utils/netnscontroller.py
Labels: enhancement

#49 Add integration testing for OTNS features
  .coveragerc
  .github/workflows/test.yml
  .gitignore
  README.md
  bootstrap.sh
  requirements.txt
  silk/node/base_node.py
  silk/node/fifteen_four_dev_board.py
  silk/tools/otns_manager.py
  silk/unit_tests/__init__.py
  silk/unit_tests/mock_device.py
  silk/unit_tests/test_otns.py
  silk/unit_tests/testcase.py
Labels: continuous-integration

#51 Add option to specify netns name when initializing a NetnsController
  .codecov.yml
  silk/device/netns_base.py
Labels: enhancement

#53 Add default log_info implementation
  silk/device/netns_base.py
Labels: bug

#54 Use platform agnostic code to get local IP
  silk/node/fifteen_four_dev_board.py
  silk/tools/otns_manager.py
  silk/utils/network.py
Labels: enhancement

#55 Allow specifying netns name for StandaloneNetworkNamespace
  .codecov.yml
  silk/device/netns_base.py
  silk/node/fifteen_four_dev_board.py
Labels: bug

#57 Add OTNS unit tests
  .github/workflows/test.yml
  .gitignore
  README.md
  silk/tests/silk_replay.py
  silk/tests/testcase.py
  silk/tools/otns_manager.py
  silk/unit_tests/fixture/child_table_log.txt
  silk/unit_tests/fixture/form_network_log.txt
  silk/unit_tests/fixture/hwconfig.ini
  silk/unit_tests/fixture/neighbor_table_log.txt
  silk/unit_tests/fixture/partition_merge_log.txt
  silk/unit_tests/fixture/router_table_log.txt
  silk/unit_tests/mock_device.py
  silk/unit_tests/mock_service.py
  silk/unit_tests/test_log_replay.py
  silk/unit_tests/test_otns.py
  silk/unit_tests/test_otns_manager.py
  silk/unit_tests/test_utils.py
  silk/unit_tests/testcase.py
Labels: continuous-integration

#56 Send DUT serial to OTNS
  silk/tools/otns_manager.py
Labels: enhancement

#58 Fix some lint warnings
  silk/device/__init__.py
  silk/device/message_item.py
  silk/device/netns_base.py
  silk/device/system_call_manager.py
  silk/hw/__init__.py
  silk/hw/hw_module.py
  silk/hw/hw_resource.py
  silk/node/__init__.py
  silk/node/base_node.py
  silk/node/fifteen_four_dev_board.py
  silk/node/sniffer_base.py
  silk/node/wpan_node.py
  silk/node/wpantund_base.py
  silk/postprocessing/ip.py
  silk/postprocessing/util.py
  silk/tests/__init__.py
  silk/tests/openthread/ot_test_add_ip6_address.py
  silk/tests/openthread/ot_test_child_table.py
  silk/tests/openthread/ot_test_inform_previous_parent.py
  silk/tests/openthread/ot_test_leader_loss.py
  silk/tests/openthread/ot_test_neighbor_table.py
  silk/tests/openthread/ot_test_on_mesh_prefix_config_gateway.py
  silk/tests/openthread/ot_test_parent_reset_child_recovery.py
  silk/tests/openthread/ot_test_partition_merge.py
  silk/tests/openthread/ot_test_scan.py
  silk/tests/openthread/ot_test_slaac_address_ncp.py
  silk/tests/silk_replay.py
  silk/tests/silk_run.py
  silk/tests/testcase.py
  silk/tools/otns_manager.py
  silk/tools/usbdevice.py
  silk/tools/watchable.py
  silk/tools/wpan_table_parser.py
  silk/tools/wpan_util.py
  silk/unit_tests/test_otns.py
  silk/unit_tests/test_otns_manager.py
  silk/utils/decorator.py
  silk/utils/jsonfile.py
  silk/utils/multipleprocess.py
  silk/utils/process.py
  silk/utils/signal.py
  silk/utils/subprocess_runner.py
Labels: continuous-integration
